### ISSUE TITLE
using non-authorized MAC addresses

### ISSUE THREAD

**Issue by yarnik1** [pontem-network/bootstrap#7]
Hetzner says that outgoing packets are using non-authorized MAC addresses.
I did an audit with tcpdump  and saw that the IP addresses from which the packets leave do not belong to me.
13:14:39.393565 IP 62.141.44.38.30333 > 172.18.0.2.33060: Flags [P.], seq 708:1412, ack 1, win 130, options [nop,nop,TS val 4238507880 ecr 1723023175], length 704

**Comment by Krishnacore** [comment]
> Hetzner says that outgoing packets are using non-authorized MAC addresses.
> I did an audit with tcpdump and saw that the IP addresses from which the packets leave do not belong to me.
> 13:14:39.393565 IP 62.141.44.38.30333 > 172.18.0.2.33060: Flags [P.], seq 708:1412, ack 1, win 130, options [nop,nop,TS val 4238507880 ecr 1723023175], length 704

I've done a little research on this issue and it seems to be a fairly common problem among Hetzner users. It is most often related to, but not limited to, the use of Docker. But it has nothing to do with Pontem specifically. 

It also seems that there is no simple and universal solution to this problem. I can suggest trying to change the network configuration in the docker-compose.yml file. Instead of 
```
ports:
      - "127.0.0.1:9934:9934"   # relaychain rpc
      - "127.0.0.1:9945:9945"   # relaychain ws
      - "30334:30334"           # relaychain p2p
      - "127.0.0.1:9933:9933"   # parachain rpc
      - "127.0.0.1:9944:9944"   # parachain ws
      - "30333:30333"           # parachain p2p
      - "9615:9615"             # prometheus metrics
```
Use: 
```
network_mode: host
```
